version: '3.4'

services:
  backend:
    image: rfid-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run dev